### ISSUE TITLE
Not able to complete installation

### ISSUE THREAD

**Issue by SarahMars** [marcoesposito1988/tf_bag#5]
I'm sorry for the simple question, but I am not able to import this package.

I tried to install the package with 
`pip install -e git+https://github.com/IFL-CAMP/tf_bag#egg=tf_bag`

and got this message 

```
Obtaining tf_bag from git+https://github.com/IFL-CAMP/tf_bag#egg=tf_bag
  Cloning https://github.com/IFL-CAMP/tf_bag to ./src/tf-bag
    Complete output from command python setup.py egg_info:
    running egg_info
    creating src/tf_bag.egg-info
    writing src/tf_bag.egg-info/PKG-INFO
    writing top-level names to src/tf_bag.egg-info/top_level.txt
    writing dependency_links to src/tf_bag.egg-info/dependency_links.txt
    writing manifest file 'src/tf_bag.egg-info/SOURCES.txt'
    error: package directory 'src/tf_bag' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/sarah/practice_ws/src/sim_eval/sim_eval/src/tf-bag/

```

Am I installing it incorrectly?
Any help would be appreciated.
Thank you in advance.

**Comment by gabrieletiboni** [comment]
Same problem here. I'm stuck and cannot install the package.

**Comment by marcoesposito1988** [comment]
My bad, I didn't add an installation section to the README.

This package was designed to be added to a ROS workspace. It is then available through `rospython` (which basically adds the needed directories to the `PYTHONPATH`).

Adapting the package to be usable without a full ROS installation looks very hard to me, given the dependency on `rospy` and `rosbag`. However, I would welcome any PR that makes this possible.

I will update the docs with a friendly `Getting started` section. Thanks for reporting!

**Comment by gabrieletiboni** [comment]
Could you give me more info on how to "add the package to a ROS workspace" please? I do have a full ROS installation.

In the meantime, I created the new directory "src/tf_bag/" and the installation through pip worked. I wonder whether this is enough

**Comment by SarahMars** [comment]
Thank you so much for the friendly instructions!
I can now compile it!
